# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/remy/docs/code/tmp/mehteor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/remy/docs/code/tmp/mehteor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/remy/docs/code/tmp/mehteor/CMakeFiles /home/remy/docs/code/tmp/mehteor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/remy/docs/code/tmp/mehteor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/core/system.o: src/core/system.cpp.o
.PHONY : src/core/system.o

# target to build an object file
src/core/system.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/system.cpp.o
.PHONY : src/core/system.cpp.o

src/core/system.i: src/core/system.cpp.i
.PHONY : src/core/system.i

# target to preprocess a source file
src/core/system.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/system.cpp.i
.PHONY : src/core/system.cpp.i

src/core/system.s: src/core/system.cpp.s
.PHONY : src/core/system.s

# target to generate assembly for a file
src/core/system.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/system.cpp.s
.PHONY : src/core/system.cpp.s

src/glew.o: src/glew.c.o
.PHONY : src/glew.o

# target to build an object file
src/glew.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/glew.c.o
.PHONY : src/glew.c.o

src/glew.i: src/glew.c.i
.PHONY : src/glew.i

# target to preprocess a source file
src/glew.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/glew.c.i
.PHONY : src/glew.c.i

src/glew.s: src/glew.c.s
.PHONY : src/glew.s

# target to generate assembly for a file
src/glew.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/glew.c.s
.PHONY : src/glew.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/soil/SOIL.o: src/soil/SOIL.c.o
.PHONY : src/soil/SOIL.o

# target to build an object file
src/soil/SOIL.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/SOIL.c.o
.PHONY : src/soil/SOIL.c.o

src/soil/SOIL.i: src/soil/SOIL.c.i
.PHONY : src/soil/SOIL.i

# target to preprocess a source file
src/soil/SOIL.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/SOIL.c.i
.PHONY : src/soil/SOIL.c.i

src/soil/SOIL.s: src/soil/SOIL.c.s
.PHONY : src/soil/SOIL.s

# target to generate assembly for a file
src/soil/SOIL.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/SOIL.c.s
.PHONY : src/soil/SOIL.c.s

src/soil/image_DXT.o: src/soil/image_DXT.c.o
.PHONY : src/soil/image_DXT.o

# target to build an object file
src/soil/image_DXT.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/image_DXT.c.o
.PHONY : src/soil/image_DXT.c.o

src/soil/image_DXT.i: src/soil/image_DXT.c.i
.PHONY : src/soil/image_DXT.i

# target to preprocess a source file
src/soil/image_DXT.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/image_DXT.c.i
.PHONY : src/soil/image_DXT.c.i

src/soil/image_DXT.s: src/soil/image_DXT.c.s
.PHONY : src/soil/image_DXT.s

# target to generate assembly for a file
src/soil/image_DXT.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/image_DXT.c.s
.PHONY : src/soil/image_DXT.c.s

src/soil/image_helper.o: src/soil/image_helper.c.o
.PHONY : src/soil/image_helper.o

# target to build an object file
src/soil/image_helper.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/image_helper.c.o
.PHONY : src/soil/image_helper.c.o

src/soil/image_helper.i: src/soil/image_helper.c.i
.PHONY : src/soil/image_helper.i

# target to preprocess a source file
src/soil/image_helper.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/image_helper.c.i
.PHONY : src/soil/image_helper.c.i

src/soil/image_helper.s: src/soil/image_helper.c.s
.PHONY : src/soil/image_helper.s

# target to generate assembly for a file
src/soil/image_helper.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/image_helper.c.s
.PHONY : src/soil/image_helper.c.s

src/soil/stb_image_aug.o: src/soil/stb_image_aug.c.o
.PHONY : src/soil/stb_image_aug.o

# target to build an object file
src/soil/stb_image_aug.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/stb_image_aug.c.o
.PHONY : src/soil/stb_image_aug.c.o

src/soil/stb_image_aug.i: src/soil/stb_image_aug.c.i
.PHONY : src/soil/stb_image_aug.i

# target to preprocess a source file
src/soil/stb_image_aug.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/stb_image_aug.c.i
.PHONY : src/soil/stb_image_aug.c.i

src/soil/stb_image_aug.s: src/soil/stb_image_aug.c.s
.PHONY : src/soil/stb_image_aug.s

# target to generate assembly for a file
src/soil/stb_image_aug.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/soil/stb_image_aug.c.s
.PHONY : src/soil/stb_image_aug.c.s

src/ui/canvas.o: src/ui/canvas.cpp.o
.PHONY : src/ui/canvas.o

# target to build an object file
src/ui/canvas.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/canvas.cpp.o
.PHONY : src/ui/canvas.cpp.o

src/ui/canvas.i: src/ui/canvas.cpp.i
.PHONY : src/ui/canvas.i

# target to preprocess a source file
src/ui/canvas.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/canvas.cpp.i
.PHONY : src/ui/canvas.cpp.i

src/ui/canvas.s: src/ui/canvas.cpp.s
.PHONY : src/ui/canvas.s

# target to generate assembly for a file
src/ui/canvas.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/canvas.cpp.s
.PHONY : src/ui/canvas.cpp.s

src/ui/shader.o: src/ui/shader.cpp.o
.PHONY : src/ui/shader.o

# target to build an object file
src/ui/shader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/shader.cpp.o
.PHONY : src/ui/shader.cpp.o

src/ui/shader.i: src/ui/shader.cpp.i
.PHONY : src/ui/shader.i

# target to preprocess a source file
src/ui/shader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/shader.cpp.i
.PHONY : src/ui/shader.cpp.i

src/ui/shader.s: src/ui/shader.cpp.s
.PHONY : src/ui/shader.s

# target to generate assembly for a file
src/ui/shader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/shader.cpp.s
.PHONY : src/ui/shader.cpp.s

src/ui/shaderprogram.o: src/ui/shaderprogram.cpp.o
.PHONY : src/ui/shaderprogram.o

# target to build an object file
src/ui/shaderprogram.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/shaderprogram.cpp.o
.PHONY : src/ui/shaderprogram.cpp.o

src/ui/shaderprogram.i: src/ui/shaderprogram.cpp.i
.PHONY : src/ui/shaderprogram.i

# target to preprocess a source file
src/ui/shaderprogram.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/shaderprogram.cpp.i
.PHONY : src/ui/shaderprogram.cpp.i

src/ui/shaderprogram.s: src/ui/shaderprogram.cpp.s
.PHONY : src/ui/shaderprogram.s

# target to generate assembly for a file
src/ui/shaderprogram.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/shaderprogram.cpp.s
.PHONY : src/ui/shaderprogram.cpp.s

src/ui/texture.o: src/ui/texture.cpp.o
.PHONY : src/ui/texture.o

# target to build an object file
src/ui/texture.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/texture.cpp.o
.PHONY : src/ui/texture.cpp.o

src/ui/texture.i: src/ui/texture.cpp.i
.PHONY : src/ui/texture.i

# target to preprocess a source file
src/ui/texture.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/texture.cpp.i
.PHONY : src/ui/texture.cpp.i

src/ui/texture.s: src/ui/texture.cpp.s
.PHONY : src/ui/texture.s

# target to generate assembly for a file
src/ui/texture.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/texture.cpp.s
.PHONY : src/ui/texture.cpp.s

src/ui/vbo.o: src/ui/vbo.cpp.o
.PHONY : src/ui/vbo.o

# target to build an object file
src/ui/vbo.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/vbo.cpp.o
.PHONY : src/ui/vbo.cpp.o

src/ui/vbo.i: src/ui/vbo.cpp.i
.PHONY : src/ui/vbo.i

# target to preprocess a source file
src/ui/vbo.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/vbo.cpp.i
.PHONY : src/ui/vbo.cpp.i

src/ui/vbo.s: src/ui/vbo.cpp.s
.PHONY : src/ui/vbo.s

# target to generate assembly for a file
src/ui/vbo.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/vbo.cpp.s
.PHONY : src/ui/vbo.cpp.s

src/ui/vertexattribute.o: src/ui/vertexattribute.cpp.o
.PHONY : src/ui/vertexattribute.o

# target to build an object file
src/ui/vertexattribute.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/vertexattribute.cpp.o
.PHONY : src/ui/vertexattribute.cpp.o

src/ui/vertexattribute.i: src/ui/vertexattribute.cpp.i
.PHONY : src/ui/vertexattribute.i

# target to preprocess a source file
src/ui/vertexattribute.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/vertexattribute.cpp.i
.PHONY : src/ui/vertexattribute.cpp.i

src/ui/vertexattribute.s: src/ui/vertexattribute.cpp.s
.PHONY : src/ui/vertexattribute.s

# target to generate assembly for a file
src/ui/vertexattribute.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/vertexattribute.cpp.s
.PHONY : src/ui/vertexattribute.cpp.s

src/ui/vertexattributes.o: src/ui/vertexattributes.cpp.o
.PHONY : src/ui/vertexattributes.o

# target to build an object file
src/ui/vertexattributes.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/vertexattributes.cpp.o
.PHONY : src/ui/vertexattributes.cpp.o

src/ui/vertexattributes.i: src/ui/vertexattributes.cpp.i
.PHONY : src/ui/vertexattributes.i

# target to preprocess a source file
src/ui/vertexattributes.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/vertexattributes.cpp.i
.PHONY : src/ui/vertexattributes.cpp.i

src/ui/vertexattributes.s: src/ui/vertexattributes.cpp.s
.PHONY : src/ui/vertexattributes.s

# target to generate assembly for a file
src/ui/vertexattributes.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/vertexattributes.cpp.s
.PHONY : src/ui/vertexattributes.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... src/core/system.o"
	@echo "... src/core/system.i"
	@echo "... src/core/system.s"
	@echo "... src/glew.o"
	@echo "... src/glew.i"
	@echo "... src/glew.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/soil/SOIL.o"
	@echo "... src/soil/SOIL.i"
	@echo "... src/soil/SOIL.s"
	@echo "... src/soil/image_DXT.o"
	@echo "... src/soil/image_DXT.i"
	@echo "... src/soil/image_DXT.s"
	@echo "... src/soil/image_helper.o"
	@echo "... src/soil/image_helper.i"
	@echo "... src/soil/image_helper.s"
	@echo "... src/soil/stb_image_aug.o"
	@echo "... src/soil/stb_image_aug.i"
	@echo "... src/soil/stb_image_aug.s"
	@echo "... src/ui/canvas.o"
	@echo "... src/ui/canvas.i"
	@echo "... src/ui/canvas.s"
	@echo "... src/ui/shader.o"
	@echo "... src/ui/shader.i"
	@echo "... src/ui/shader.s"
	@echo "... src/ui/shaderprogram.o"
	@echo "... src/ui/shaderprogram.i"
	@echo "... src/ui/shaderprogram.s"
	@echo "... src/ui/texture.o"
	@echo "... src/ui/texture.i"
	@echo "... src/ui/texture.s"
	@echo "... src/ui/vbo.o"
	@echo "... src/ui/vbo.i"
	@echo "... src/ui/vbo.s"
	@echo "... src/ui/vertexattribute.o"
	@echo "... src/ui/vertexattribute.i"
	@echo "... src/ui/vertexattribute.s"
	@echo "... src/ui/vertexattributes.o"
	@echo "... src/ui/vertexattributes.i"
	@echo "... src/ui/vertexattributes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

