set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER i486-mingw32-gcc)
set(CMAKE_CXX_COMPILER i486-mingw32-g++)
set(CMAKE_RC_COMPILER i486-mingw32-windres)

set(MINGW)

set(CMAKE_FIND_ROOT_PATH /usr/i486-mingw32)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_LIBRARY_SUFFIXES .lib .a ${CMAKE_FIND_LIBRARY_SUFFIXES})
